[package]
name = "pam_oauth2_device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pam_oauth2_device"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.37"
log = "0.4.21"
oauth2 = "4.4.2"
pam-bindings = "0.1.1"
qrcode = "0.14.0"
serde = { varsion = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
simplelog = "0.12.2"
url = { version = "2.5.0", features = ["serde"] }
